project:
  type: website

website:
  title: "Ari P.S. Prasojo"
  description: "Personal website of Ari P.S. Prasojo"
  site-url: "https://aripurwantosp.github.io"
  favicon: images/ari-photo.jpg

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publications
      - href: software/index.qmd
        text: Software
      - href: projects/index.qmd
        text: Projects
      - href: about.qmd
        text: About

  page-footer:
    left: © 2025 Ari Purwanto Sarwo Prasojo 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: right
    smooth-scroll: true