project:
  type: website

website:
  title: "Ari P S Prasojo"
  description: "Personal website of Ari P.S. Prasojo"
  site-url: "https://aripurwantosp.github.io"
  favicon: images/ari-photo.jpg

  navbar:
    background: "#234460"
    left:
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publications
      - href: software/index.qmd
        text: Software
      - href: projects/index.qmd
        text: Projects
      - href: about.qmd
        text: About

  page-footer:
    left: © 2025 Ari Purwanto Sarwo Prasojo 

format:
  html:
    theme: flatly
    include-in-header:
      - text: |
          <!-- Font Awesome -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
          <!-- Academicons -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css">
    css: styles.css
    toc: true
    toc-location: right
    smooth-scroll: true